name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "镜像版本号 (例如 v1.2.6)"
        required: true
        default: "latest"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            luffy168/115uploader:latest
            luffy168/115uploader:${{ github.event.inputs.version }}
