name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"   # 例如 v1.0.0 v1.0.1

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            luffy168/115uploader:latest
            ${{ startsWith(github.ref, 'refs/tags/') && format('luffy168/115uploader:{0}', github.ref_name) || '' }}
